<a href="https://colab.research.google.com/github/cdivy/git_test/blob/main/Automl.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

We are an AutoML product, we are looking for a data scientist, who can innovate, maintain code.
This is a perfect test for us to know if the candidate can start working from day 1. This test can be done in a few hours if you have been dealing with these sorts of problems. If not, it will take some time.
We are providing you a small dataset. There are 2 target variables in it. One is a categorical variable (Target Satisfaction) and another is a numeric variable (Target Salary). 

The task is - 
You have to clean this data, prepare it for ML models, build more features and ultimately build a random forest (scikit).
Split the dataset into 80:20, train:test. 
Print the Weighted F1 on test dataset (target_satisfaction) and RMSE (Target_salary)

Please note - 
If you do this problem without any cleaning or building any additional features, you won't get the RMSE or good F1. There are lots of variables which need feature engineering. 

Follow the usual data science process. 

Please if you plan to submit any random value, we won’t be giving you a call , since even before running your code in google colab, we know the possible range of answers. 

Please don’t print graphs, visualizations, it makes readability of code lower. 

Do well comment on the code. Commenting the code well is very important from a readability point of view. 

Before attempting this, few more things to let you know, so the expectations are right and you attempt only when you are sure. 
You have to be very good with python and data science concepts.
Please do not attempt it if you are not very good with data science, as this is not a training internship and we expect you to contribute from day 1, with our minimal assistance. 

Google response form - 

https://forms.gle/ep4EYQJiXrmMsA497



Dataset - 
https://drive.google.com/file/d/16plggcGFOBEvjiYK65--Z6SmRwdeDbUy/view?usp=sharing

In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

In [37]:
df = pd.read_csv('/content/salary-satisfaction.csv',sep=',',encoding='mac_roman',engine='python')

In [24]:
df['Civil Service Title'].value_counts()

COMMUNITY COORDINATOR             182
AGENCY ATTORNEY                   112
CIVIL ENGINEER                     87
CITY RESEARCH SCIENTIST            83
CONSTRUCTION PROJECT MANAGER       72
                                 ...
ASSOCIATE CALL CENTER REPRESEN      1
CASEWORKER                          1
COMPUTER SERVICE TECHNICIAN (C      1
DEPUTY CHIEF OF OPERATIONS (PA      1
ADMINISTRATIVE MANAGER              1
Name: Civil Service Title, Length: 312, dtype: int64

In [40]:
df.head()

         id  ...                                             Tittle
0  68407277  ...     Account Manager CONTRACT REVIEWER (OFFICE OF L
1  68355089  ...  EXECUTIVE DIRECTOR, BUSINESS DEVELOPMENT ADMIN...
2  68341763  ...  Maintenance Worker - Technical Services-Heatin...
3  66310712  ...  Maintenance Worker - Technical Services-Heatin...
4  68476807  ...                          Temporary Painter PAINTER

[5 rows x 82 columns]

In [39]:
df['Tittle']

0          Account Manager CONTRACT REVIEWER (OFFICE OF L
1       EXECUTIVE DIRECTOR, BUSINESS DEVELOPMENT ADMIN...
2       Maintenance Worker - Technical Services-Heatin...
3       Maintenance Worker - Technical Services-Heatin...
4                               Temporary Painter PAINTER
                              ...
2941    Senior Mechanical Cost Estimator CONSTRUCTION ...
2942    Senior Mechanical Cost Estimator CONSTRUCTION ...
2943         Conversion Coordinator COMMUNITY COORDINATOR
2944         Conversion Coordinator COMMUNITY COORDINATOR
2945          Administrative Associate CLERICAL ASSOCIATE
Name: Tittle, Length: 2946, dtype: object

In [16]:
df.shape

(2946, 83)

In [38]:
df['Tittle'] = df['Business Title'] + ' '+ df['Civil Service Title']
df = df.drop(columns=['Business Title','Civil Service Title'],axis=1)

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2946 entries, 0 to 2945
Data columns (total 83 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   id                          2946 non-null   int64
 1   Target_Salary               2946 non-null   float64
 2   Target_Satisfied            2946 non-null   int64
 3   LOAN_AMT                    2946 non-null   object
 4   Business Title              2946 non-null   object
 5   Civil Service Title         2946 non-null   object
 6   Division/Work Unit          2946 non-null   object
 7   Job Description             2946 non-null   object
 8   Minimum Qual Requirements   2926 non-null   object
 9   Preferred Skills            2553 non-null   object
 10  Additional Information      1854 non-null   object
 11  To Apply                    2945 non-null   object
 12  Hours/Shift                 884 non-null    object
 13  Residency Requirement       2942 non-null   object
 14  Posting Date                2942 non-null   object
 15  Posting Updated             2942 non-null   object
 16  Process Date                2942 non-null   object
 17  FormalEducation             2894 non-null   object
 18  UndergradMajor              2624 non-null   object
 19  CompanySize                 2946 non-null   object
 20  DevType                     2901 non-null   object
 21  YearsCoding                 2943 non-null   object
 22  YearsCodingProf             2538 non-null   object
 23  HopeFiveYears               2477 non-null   object
 24  JobSearchStatus             2511 non-null   object
 25  LastNewJob                  2499 non-null   object
 26  UpdateCV                    2089 non-null   object
 27  CommunicationTools          2023 non-null   object
 28  TimeFullyProductive         2052 non-null   object
 29  EducationTypes              2128 non-null   object
 30  SelfTaughtTypes             1812 non-null   object
 31  TimeAfterBootcamp           221 non-null    object
 32  HackathonReasons            849 non-null    object
 33  AgreeDisagree1              2133 non-null   object
 34  AgreeDisagree2              2133 non-null   object
 35  AgreeDisagree3              2139 non-null   object
 36  LanguageWorkedWith          2447 non-null   object
 37  LanguageDesireNextYear      2279 non-null   object
 38  DatabaseWorkedWith          2130 non-null   object
 39  DatabaseDesireNextYear      1831 non-null   object
 40  PlatformWorkedWith          2070 non-null   object
 41  PlatformDesireNextYear      1909 non-null   object
 42  FrameworkWorkedWith         1633 non-null   object
 43  FrameworkDesireNextYear     1731 non-null   object
 44  IDE                         2360 non-null   object
 45  OperatingSystem             2377 non-null   object
 46  Methodology                 1991 non-null   object
 47  VersionControl              2332 non-null   object
 48  CheckInCode                 2319 non-null   object
 49  AIDangerous                 2000 non-null   object
 50  AIInteresting               2076 non-null   object
 51  AIResponsible               2070 non-null   object
 52  AIFuture                    2196 non-null   object
 53  Age                         2027 non-null   object
 54  term                        2946 non-null   object
 55  loan_status                 2946 non-null   object
 56  pymnt_plan                  2946 non-null   object
 57  orignal_website_directory   2946 non-null   object
 58  purpose                     2946 non-null   object
 59  title                       2882 non-null   object
 60  zip_code                    2946 non-null   object
 61  addr_state                  2946 non-null   object
 62  dti                         2946 non-null   float64
 63  earliest_cr_line            2946 non-null   object
 64  last_pymnt_d                2946 non-null   object
 65  last_pymnt_amnt             2946 non-null   float64
 66  next_pymnt_d                336 non-null    object
 67  last_credit_pull_d          2946 non-null   object
 68  Time                        2946 non-null   object
 69  emp_length                  715 non-null    object
 70  your_favoritearticle_today  2945 non-null   object
 71  url                         2946 non-null   object
 72  Email                       1941 non-null   object
 73  homeaddress                 2629 non-null   object
 74  latitude                    2629 non-null   float64
 75  longitude                   2629 non-null   float64
 76  PHONE                       715 non-null    object
 77  officeaddress               2407 non-null   object
 78  website                     2399 non-null   object
 79  dateAdded                   2946 non-null   object
 80  previousaddress             2946 non-null   object
 81  phones                      2946 non-null   object
 82  CrimeTime                   2946 non-null   object
dtypes: float64(5), int64(2), object(76)
memory usage: 1.9+ MB